### ISSUE TITLE
Failed to load cmnative-linux-x64.node

### ISSUE THREAD

**Issue by mc23101** [yuuki-nya/chronocat-docker#3]
Failed to inject hooks Error: Failed to load cmnative-linux-x64.node
    at /root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130286
    at Object.readFileAsync (/root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:35488)
    at V (/root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130256)
    at new Promise (<anonymous>)
    at xe (/root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:1:130142)
    at dl (/root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:1468)
    at K0 (/root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:20898)
    at $0 (/root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:21188)
    at Object.<anonymous> (/root/LiteLoaderQQNT/plugins/LiteLoaderQQNT-Plugin-Chronocat/src/main.js:255:23130)
    at Module._compile (node:internal/modules/cjs/loader:1120:14)

**Comment by yuuki-nya** [comment]
什么环境，是最近镜像吗？镜像测试过没问题的，是不是更新过Linux QQ?

**Comment by mc23101** [comment]
> 什么环境，是最近镜像吗？镜像测试过没问题的，是不是更新过Linux QQ?

宿主机是乌班图22.04 内核版本5.15  使用你的docker镜像，linuxQQ没更新过

**Comment by yuuki-nya** [comment]
那很奇怪，宿主机我在unbuntu 22.04  20.04都是测试过的，我建议你删除镜像重新pull个最新的

**Comment by gclm** [comment]
最新镜像同出现找个问题

**Comment by yuuki-nya** [comment]
我复现出你们的问题了，数据固化前要按README把数据复制到宿主机，再固化，目录内容为空就会启动失败
